<?php

function cptui_register_my_cpts_mv_address_book() {

    /**
     * Post Type: Contacts.
     */

    $labels = array(
        "name" => __( "Contacts", "mooveat" ),
        "singular_name" => __( "Contact", "mooveat" ),
        "all_items" => __( "Tous les contacts", "mooveat" ),
        "add_new" => __( "Ajouter un contact", "mooveat" ),
        "edit_item" => __( "", "mooveat" ),
    );

    $args = array(
        "label" => __( "Contacts", "mooveat" ),
        "labels" => $labels,
        "description" => "Mooveat Address Book ",
        "public" => true,
        "publicly_queryable" => true,
        "show_ui" => true,
        "show_in_rest" => false,
        "rest_base" => "",
        "has_archive" => false,
        "show_in_menu" => true,
        "show_in_nav_menus" => false,
        "exclude_from_search" => true,
        "capability_type" => "post",
        "map_meta_cap" => true,
        "hierarchical" => false,
        "rewrite" => array( "slug" => "mv_address_book", "with_front" => true ),
        "query_var" => true,
        "menu_icon" => "dashicons-book-alt",
        "supports" => false,
        "taxonomies" => array( "nomenclature_beta" ),

    );

    register_post_type( "mv_address_book", $args );
}

add_action( 'init', 'cptui_register_my_cpts_mv_address_book' );


if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5aba56cc59c20',
        'title' => 'Address Book',
        'fields' => array(
            array(
                'key' => 'field_5aba57be30e52',
                'label' => 'Contact',
                'name' => 'contact',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-contacts',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5aba5bdeac18c',
                        'label' => 'Nom',
                        'name' => 'nom',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-nom',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Nom',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5aba5c26bf663',
                        'label' => 'Prénom',
                        'name' => 'first_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-firstname',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Prénom',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),/*
                    array(
                        'key' => 'field_5aba65f2459d9',
                        'label' => 'Intitulé organisation',
                        'name' => 'intitule_organisation',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Intitulé organisation',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),*/
                    array(
                        'key' => 'field_5aba6601459da',
                        'label' => 'Fonction',
                        'name' => 'fonction',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Fonction',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5aba6628459db',
                        'label' => 'WP USER',
                        'name' => 'wp_user',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'wp_user' => 'Associer à l’utilisateur Wordpress',
                        ),
                        'allow_custom' => 0,
                        'save_custom' => 0,
                        'default_value' => array(
                        ),
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                    ),
                ),
            ),
            array(
                'key' => 'field_5aba5d4a573a8',
                'label' => 'Email et réseaux',
                'name' => 'social',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-social',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5aba5d4a573a9',
                        'label' => 'Email',
                        'name' => 'email',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Email',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_5aba5d4a573aa',
                        'label' => 'Site web',
                        'name' => 'site_web',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Site web',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5aba67ba8f44d',
                        'label' => 'Facebook',
                        'name' => 'facebook',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Facebook',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5aba67c28f44e',
                        'label' => 'Twitter',
                        'name' => 'twitter',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Twitter',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5abbe1b1f1ed6',
                'label' => 'Logo',
                'name' => 'logo_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-logo',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbe1c0f1ed7',
                        'label' => 'Logo',
                        'name' => 'logo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => 1,
                        'mime_types' => '.jpg, .jpeg, .png, .gif',
                    ),
                ),
            ),
            array(
                'key' => 'field_5abbe88f78872',
                'label' => 'Classification',
                'name' => 'mv_cat_orga_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-cat-orga-grp mv-classification-grp',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbe89b78873',
                        'label' => 'Catégorie principale organisation',
                        'name' => 'categorie_principale_organisation',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cpo',
                            'id' => '',
                        ),
                        'choices' => array(
                            '' => 'Choisir'
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5abbea7e213f5',
                        'label' => 'Catégorie secondaire organisation',
                        'name' => 'categorie_secondaire_organisation',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cso',
                            'id' => '',
                        ),
                        'choices' => array(
                            '' => 'Choisir',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5aeae03eba46b',
                        'label' => 'Catégorie tertiaire organisation',
                        'name' => 'categorie_tertiaire_organisation',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cto',
                            'id' => '',
                        ),
                        'choices' => array(
                            '' => 'Choisir',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5aeae03ecatprol4a',
                        'label' => 'Catégorie Pro niveau 4',
                        'name' => 'cat_pro_level_4',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cl4',
                            'id' => '',
                        ),
                        'choices' => array(
                            '' => 'Choisir',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5aeae03ecatprol5a',
                        'label' => 'Catégorie Pro niveau 5',
                        'name' => 'cat_pro_level_5',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cl5',
                            'id' => '',
                        ),
                        'choices' => array(
                            '' => 'Choisir',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5abbe88f_orga_name',
                'label' => "Nom de l'organisation",
                'name' => 'mv_orga_name_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-cat-orga-grp',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5aeae03e_mv_ab_orga_name',
                        'label' => "Nom de l'organisation",
                        'name' => 'mv_address_book_orga_name_nomenclature',
                        'type' => 'taxonomy',
                        'instructions' => "",
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-ab-orga-name-nomenclature',
                            'id' => '',
                        ),
                        'taxonomy' => 'nomenclature_beta',
                        'field_type' => 'select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 1,
                        'load_terms' => 0,
                        'return_format' => 'object',
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_5aeae03ecatprol6a',
                        'label' => "",
                        'name' => 'cat_pro_level_6',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cl6',
                            //'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            '' => 'Choisir',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),                    
                    array(
                        'key' => 'field_5aeae03e_orga_name',
                        'label' => "Nom de l'Organisation (si introuvable dans la liste ci-dessus)",
                        'name' => 'organisation_name_to_be_added',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'organisation-name-to-be-added',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5c7e06fbac68c',
                        'label' => 'approved status',
                        'name' => 'is_approved',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'hidden',
                            'id' => '',
                        ),
                        'taxonomy' => 'nomenclature_beta',
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5abbdbbc2cc73',
                'label' => "Stade d'abonnement",
                'name' => 'stade_abo_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-typologie',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbdbca2cc74',
                        'label' => "Stade d'abonnement",
                        'name' => 'stade_abo',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'stade-abo-1' => 'Utilisateur',
                            'stade-abo-2' => 'Prospect',
                            'stade-abo-3' => 'Client',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                ),
            ),
            /*array(
                'key' => 'field_5acf65d448689',
                'label' => 'Label',
                'name' => 'label_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-typologie',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5acf65d44868b',
                        'label' => 'Label',
                        'name' => 'label',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Label Bio' => 'Label Bio',
                            'Label Restaurateur' => 'Label Restaurateur',
                            'Label spécifique' => 'Label spécifique',
                            'Marque collective' => 'Marque collective',
                            'Mention valorisante' => 'Mention valorisante',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'label',
                        'placeholder' => '',
                    ),
                ),
            ),*/
            array(
                'key' => 'field_5abbe22bf1etags',
                'label' => 'Étiquettes',
                'name' => 'mv_ab_tags_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-etiquettes',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbe238f1ed9',
                        'label' => 'Fonction dans la filière',
                        'name' => 'fonction_dans_la_filiere',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'achat' => 'Achat',
                            'vente' => 'Vente',
                            'achat/vente' => 'Achat / Vente',
                            'service' => 'Service (transformation, transport)',
                            'nonapplicable' => 'Non applicable',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5abbeae0213f7',
                        'label' => 'Catégorie(s) produit(s)',
                        'name' => 'categories_produits',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'mv-cp',
                            'id' => '',
                        ),
                        'choices' => array(

                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5b69b6f162cf6',
                        'label' => 'Label(s) / Signe(s) de qualité',
                        'name' => 'label_taxonomy',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'nomenclature_beta',
                        'field_type' => 'multi_select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 1,
                        'load_terms' => 0,
                        'return_format' => 'object',
                        'multiple' => 0,
                        'choices' => array(
                        ),
                    ),
                    array(
                        'key' => 'field_5b69b57d62cf2',
                        'label' => 'Restauration collective (délégation)',
                        'name' => 'type_restauration_collective',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'restauration-collective-type-1' => 'Restauration autogérée',
                            'restauration-collective-type-2' => 'Restauration concédée',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5b69b5f962cf3',
                        'label' => 'Restauration collective (type de cuisine)',
                        'name' => 'type_cuisine',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'cuisine-type-1' => 'Cuisine centrale',
                            'cuisine-type-2' => 'Cuisine satellite',
                            'cuisine-type-3' => 'Cuisine sur place',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5b69b64a62cf4',
                        'label' => 'Échelle administrative',
                        'name' => 'echelle_administration',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'echelle-administration-1' => 'Direction nationale',
                            'echelle-administration-2' => 'Direction régionale',
                            'echelle-administration-3' => 'Direction départementale',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'placeholder' => '',
                    )
                ),
            ),
            array(
                'key' => 'field_5abbeadf21tppo1',
                'label' => 'Profil',
                'name' => 'type_profil_grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-cp-grp',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b69b68b62cf5',
                        'label' => 'Profil utilisateur',
                        'name' => 'type_profil_personne_organisation',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'profil-type-1' => 'Utilisateur',
                            'profil-type-2' => 'Prescripteur',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'placeholder' => '',
                    )
                ),
            ),
            array(
                'key' => 'field_5abbe7b8ddcd6',
                'label' => 'Suivi actions',
                'name' => 'suivi_actions',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-suivi_actions',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbe7c1ddcd7',
                        'label' => 'To be Contacted',
                        'name' => 'to_be_contacted',
                        'type' => 'radio',
                        'instructions' => 'À contacter',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'to-be-contacted',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Oui' => 'Oui',
                            'Non' => 'Non',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5abbe801ddcd8',
                        'label' => 'Follow up',
                        'name' => 'follow_up_btn',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'dialog-opener',
                            'id' => '',
                        ),
                        'choices' => array(
                            'follow' => 'Follow up',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                ),
            ),
            array(
                'key' => 'field_5aba7886ea5ed',
                'label' => 'Téléphone',
                'name' => 'telephone-grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => 'mv-telephone-grp col-2',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5aba7886ea5ee',
                        'label' => 'Téléphone mobile',
                        'name' => 'telephone_mobile',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Téléphone mobile',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5aba7886ea5ef',
                        'label' => 'Téléphone fixe',
                        'name' => 'telephone_fixe',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Téléphone fixe',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),/*
                    array(
                        'key' => 'field_5aba7886ea5f0',
                        'label' => 'Fax',
                        'name' => 'fax',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Fax',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),*/
                ),
            ),
            array(
                'key' => 'field_5abbd7e15bd94',
                'label' => 'Adresse',
                'name' => 'adresse-grp',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => 'mv-adresse-grp col-2',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbd7e15bd95',
                        'label' => 'Numéro & rue',
                        'name' => 'numero_&_rue',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Numéro & rue',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5abbd7e15bd96',
                        'label' => 'Code postal',
                        'name' => 'code_postal',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Code postal',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5abbd7e15bd97',
                        'label' => 'Ville',
                        'name' => 'city',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Ville',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5abbd82f5bd98',
                        'label' => 'Pays',
                        'name' => 'country',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'France',
                        'placeholder' => 'Country',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5abbf245600d7',
                'label' => 'Follow up',
                'name' => 'follow_up',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'mv-followup-wrap',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5abbf2de600d8',
                        'label' => 'Date de contact',
                        'name' => 'date_de_contact',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'd/m/Y',
                        'return_format' => 'Ymd',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_5ad775586731c',
                        'label' => 'Méthode',
                        'name' => 'methode',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'email' => 'email',
                            'téléphone' => 'téléphone',
                            'emailing' => 'emailing',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5abbf31a600d9',
                        'label' => 'Contacté par',
                        'name' => 'contacte_par',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5abbf32c600da',
                        'label' => 'Réponse obtenue ?',
                        'name' => 'reponse_obtenue',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Oui' => 'Oui',
                            'Non' => 'Non',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5aeadfd2ba469',
                        'label' => 'Commentaires',
                        'name' => 'commentaires',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mv_address_book',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 0,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5ad78f288b311',
        'title' => 'Address Book Columns',
        'fields' => array(
            array(
                'key' => 'field_5ad78f2900fad',
                'label' => 'col1',
                'name' => 'col1',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'col col-1',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5aba57be30e52',
                    1 => 'field_5aba5d4a573a8',
                    2 => 'field_5abbd7e15bd94',
                    3 => 'field_5aba7886ea5ed',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5ad78fc92cf7e',
                'label' => 'col2',
                'name' => 'col2',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'col col-2',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5abbeadf21tppo1',
                    1 => 'field_5abbe88f_orga_name',
                    2 => 'field_5abbe88f78872',
                    3 => 'field_5abbdbbc2cc73',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5ad790002cf7f',
                'label' => 'col3',
                'name' => 'col3',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'col col-3',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5abbe1b1f1ed6',
                    1 => 'field_5abbe22bf1etags',
                    2 => 'field_5abbe7b8ddcd6',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5ad7996d33acf',
                'label' => 'other fields',
                'name' => 'other_fields',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5abbf245600d7',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mv_address_book',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5ca36e2a6856f',
        'title' => 'Beta Nomenclature New Organizations',
        'fields' => array(
            array(
                'key' => 'field_5ca36e42d33e9',
                'label' => 'Creation Date',
                'name' => 'creation_date',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ca36e9dd33ea',
                'label' => 'Creater Username',
                'name' => 'creater_username',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ca386a95142f',
                'label' => 'Status',
                'name' => 'status',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'pending' => 'Pending',
                    'valid' => 'Valid',
                    'refused' => 'Refused',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'return_format' => 'array',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5ca75c7648d65',
                'label' => 'Is New Org',
                'name' => 'is_new_org',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'nomenclature_beta',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;